### ISSUE TITLE
Possible to specify overloaded symbols in mapping file?

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1219]
Hi!

I have come across a very strange edge case: `std::abs(int)` is only available in `cstdlib`, and `std::abs(float)` is only available in `cmath` when building for an older compiler. [Repro](https://godbolt.org/z/c71KjT88q). 

Is there a good way I can express this in the mapping file in IWYU? Preferably I would like to avoid polluting the code with pragmas or with preprocessor directives to conditionally include based on compiler.

Thanks!

**Comment by kilroyd** [comment]
cppreference says that both [int](https://en.cppreference.com/w/cpp/numeric/math/abs) and [float](https://en.cppreference.com/w/cpp/numeric/math/fabs) versions should be available from both headers. If you map `std::abs` to both `<cmath>` and `<cstdlib>`, IWYU should allow either header to satisfy the abs usage. I think you're then left with the corner case where IWYU tries to get you to remove one of the headers as you have the other header present already, and nothing else is being used from it.

If you're not using `std::abs(float)` in a template, you could try use `std::fabs()` instead as it's only in `<cmath>`. [godbolt](https://godbolt.org/z/oh8WhGzGj)

**Comment by kilroyd** [comment]
Since I've been playing with the libc++ mappings recently, I've been having a play with this example. As I suspected, IWYU does suggest removing one of the headers with the mappings set up that way, and using `std::fabs` does work around this.

Personally, I think you should #if one of the includes based on libc++ version `#if defined(_LIBCPP_VERSION) && _LIBCPP_VERSION < 90000` - this best expresses the fact that you only need the include for that stdlib version (it is fixed in 9.0.0 apparently)

**Comment by carlosgalvezp** [comment]
Thanks for the advice! Will follow your tips, we can close the ticket :)

**Comment by bolshakov-a** [comment]
FWIW, a discussion about overloaded functions in symbol mappings is here: #1879.
