### ISSUE TITLE
no success

### ISSUE THREAD

**Issue by PaltryProgrammer** [include-what-you-use/include-what-you-use#1223]
thank you for providing iwyu . however i have been unable to get success w/ it . perhaps i am utilizing it incorrectly . upon applying the changes recommended to my source both Clang and VS report many errors . my source files compile w/o error under Clang and VS in original version . the ReadMe.md states a Caveat i.e.
> It was originally written to work specifically in the Google source tree, and may make assumptions, or have gaps, that are immediately and embarrassingly evident in other types of code.

i do not know what a Google source tree is nor have i been successful in learning of same via internet search so am not utilizing it whatever it is .  is this the reason for my lack of success ? i await your kind reply

**Comment by kimgr** [comment]
The caveat in the README means that `include-what-you-use` was originally written at Google, to work on Google's internal source code. All Google contributors have since left the project, and we no longer have any close coupling to the company, but there may be residual assumptions that code is designed a certain way that was common in Google at the time (e.g. no exceptions, pre-C++11 language standard, etc).

It is IWYU's goal to preserve the program's correctness and behavior, but as the README also mentions, we're at alpha quality, at best. If you can isolate examples of what's being wrongfully added/removed, we can discuss those and try to make progress.

**Comment by PaltryProgrammer** [comment]
thank you for your kind reply . may i please inquire the best manner in which to proceed . i can provide a cpp source , its' 70 included headers , the output of iwyu whilst processing original source which generated no compile errors , also output of iwyu whilst processing source again this time w/ iwyu recommended includes which resulted in many compile errors , also the batch file which set up the environment and invoked iwyu .

**Comment by kimgr** [comment]
I think it's probably easier for you to do the analysis in the comfort of your own environment.

You probably have a good idea already of which headers are wrongfully removed. See if you can find a pattern to it (you can get more info on IWYU's analysis by passing `-Xiwyu -v3` (or higher) on the `include-what-you-use` command-line) and if it's possible to reduce it to something that demonstrates the problem without all your local context.

**Comment by PaltryProgrammer** [comment]
the attached zip of two very simple cpp and h files demonstrate iwyu fail . kind regards
[iwyu_fail.zip](https://github.com/include-what-you-use/include-what-you-use/files/11160348/iwyu_fail.zip)

**Comment by kilroyd** [comment]
Your example is using C++ 20 `concept` - IWYU does not currently support C++ 20, so won't handle this properly. That said, the output of IWYU:

```
% ~/iwyu-build/bin/include-what-you-use -std=c++20 iwyu_fail.cpp -Xiwyu --check_also="MAKER.H"
In file included from iwyu_fail.cpp:2:
./MAKER.H:2:9: warning: #include ./MAKER.H [-W#pragma-messages]
#pragma message("#include " __FILE__ )
        ^

MAKER.H should add these lines:
#include <__concepts/same_as.h>  // for same_as

MAKER.H should remove these lines:

The full include-list for MAKER.H:
#include <__concepts/same_as.h>  // for same_as
---

iwyu_fail.cpp should add these lines:

iwyu_fail.cpp should remove these lines:
- #include <concepts>  // lines 1-1

The full include-list for iwyu_fail.cpp:
#include "MAKER.H"  // for MAKERCLASS
```

The warning on MAKER.H line 2 is a result of the pragma.

Because I'm on MacOs, I get a suggestion to include `__concept/same_as.h` which is just where the standard library (libc++) has defined `std::same_as` on my system. You may not see this, or get a different location. If you do get a different location, it's just a case of a missing mapping for `std::same_as`. This is part of the C++ 20 concept feature, so it's not surprising if this is missing at the moment.

The suggestion to remove `<concept>` from `iwyu_fail.cpp` is correct - the only thing being used here is the macro `MAKERCLASS`. 

Taking a step back though - it looks like you're using macros to define your own language / syntax. By all means do so - but you will probably only have a limited audience prepared to put in the effort to help debug any issues. Instead, I'd recommend sticking to a standard'ish C++ style (for examples see public C++ code in LLVM, or Google repos).

**Comment by PaltryProgrammer** [comment]
thank you for your helpful response . may i please request direction to page which documents language versions supported . despite many clicks i was unable to locate same . as for concepts the Clang page seems to indicate almost total support .

**Comment by kimgr** [comment]
IWYU is not part of the Clang project, it builds upon it.

So Clang can parse, reason about and generate code for concepts and all other listed features, but that does not mean IWYU can do use-analysis for them. We don't have a listing of supported language features in the IWYU project.

A good rule of thumb is that we have reasonable support for C++98, and then progressively weaker support for C++11, C++17, C++20 and later. We try to fix language support on a case-by-case basis as people report issues.

**Comment by kimgr** [comment]
I don't think there's anything concrete we can follow up on here, I'll close this issue. Please reopen if I've overlooked some open question.
