### ISSUE TITLE
Segfault when trying to analyze file with precompiled header added via command line

### ISSUE THREAD

**Issue by ts826848** [include-what-you-use/include-what-you-use#1230]
I ran into a segfault when trying to set up precompiled headers in a CMake-based project.

The immediate cause is [this bit in iwyu.cc](https://github.com/kimgr/include-what-you-use/blob/c30cee2ee6eca80ab341bfb5a56af03d9888aac7/iwyu.cc#L4020):

```cpp
  bool VisitTagDecl(clang::TagDecl* decl) {
    // snip
    if (IsForwardDecl(decl)) {
      // snip
      preprocessor_info().FileInfoFor(CurrentFileEntry())->AddForwardDeclare(
          decl_to_fwd_declare, definitely_keep_fwd_decl);
    }
    return Base::VisitTagDecl(decl);
  }
```

`preprocessor_info().FileInfoFor(CurrentFileEntry())` returns `nullptr`, which causes a `this` dereference further down the stack to segfault.

I was able to get the test case reduced to:

`main.cpp`:
```cpp
#include "main.hpp"
```

`main.hpp`:
```cpp
#ifndef MAIN_HPP_INCLUDED
#define MAIN_HPP_INCLUDED
#include "core.hpp"
ADD()
#endif
```

`core.hpp`:
```cpp
#define ADD(...) namespace { struct data; }
```

`driver.sh`, derived from the CMake-generated command line:
```sh
#!/bin/sh

/usr/local/opt/llvm/bin/clang++ \
	-I. \
	-std=c++20 \
	-fpch-instantiate-templates \
	-Xclang -emit-pch \
	-Xclang -include \
	-Xclang main.hpp \
	-x c++-header \
	-o cmake_pch.hxx.pch \
	-c empty.cpp \
	&& \
/usr/local/opt/include-what-you-use/bin/include-what-you-use \
	-std=c++20 \
	-Xclang -include-pch \
	-Xclang cmake_pch.hxx.pch \
	-c main.cpp
```

Trimmed verbose log:
```
Setting verbose-level to 20
<Snip: Adding mappings and search paths>
[ #include    ]  (main.cpp)
Found include: <built-in>:-1 -> main.cpp
Added an #include: <built-in> ->
Added to main compilation unit: main.cpp
[ #include    ]  (<built-in>)
[ Exiting to  ] main.cpp:1:1
[ (#include)  ] "main.hpp" (main.hpp)
Found include: main.cpp:1 -> main.hpp
Adding main.hpp as associated header for main.cpp
Marked main.hpp as associated header of main.cpp.
Added an #include: main.cpp -> "main.hpp"
[ Exiting to  ] <invalid loc>
Intends-to-provide for main.cpp:
   main.cpp
   main.hpp
Intends-to-provide for main.hpp:
   main.hpp
<invalid loc>: (0) [ TranslationUnitDecl ] 0x7fe533848808
<invalid loc>: (1) [ TypedefDecl ] 0x7fe533849508 typedef __int128 __int128_t
<invalid loc>: (2) [ BuiltinTypeLoc ] __int128
<invalid loc>: (1) [ TypedefDecl ] 0x7fe533849580 typedef unsigned __int128 __uint128_t
<invalid loc>: (2) [ BuiltinTypeLoc ] unsigned __int128
<invalid loc>: (1) [ TypedefDecl ] 0x7fe5338493d0 typedef __NSConstantString_tag __NSConstantString
<invalid loc>: (2) [ RecordTypeLoc ] struct __NSConstantString_tag
<invalid loc>: (1) [ TypedefDecl ] 0x7fe533849628 typedef char *__builtin_ms_va_list
<invalid loc>: (2) [ PointerTypeLoc ] char *
<invalid loc>: (3) [ BuiltinTypeLoc ] char
<invalid loc>: (1) [ TypedefDecl ] 0x7fe533836a30 typedef __va_list_tag __builtin_va_list[1]
<invalid loc>: (2) [ ConstantArrayTypeLoc ] struct __va_list_tag[1]
<invalid loc>: (3) [ RecordTypeLoc ] struct __va_list_tag
/tmp/crash/main.hpp:4:1 <Spelling=/tmp/crash/core.hpp:1:28>: (1) [ NamespaceDecl ] 0x7fe533849460 namespace {
}
/tmp/crash/main.hpp:4:1 <Spelling=/tmp/crash/core.hpp:1:37>: (2) [ CXXRecordDecl ] 0x7fe533836af0 struct data
./driver.sh: line 19: 24837 Segmentation fault: 11
```

This is on macOS Monterey 12.6.3, using include-what-you-use 0.20 (c30cee2ee6ec, subst-type-traversal branch) and Homebrew clang 16.0.0 (08d094a0e457360ad8b94b017d2dc277e697ca76, tag llvmorg-16.0.0)

**Comment by kimgr** [comment]
Interesting. It looks like `core.hpp` is never seen as an include when part of the PCH, so it doesn't exist in the FileInfo-map. Not sure if Clang has any machinery for getting preprocessor-like callbacks when loading the PCH.

**Comment by kimgr** [comment]
Something gets confused when `main.hpp` is both used for precompiled header and explicitly included in the source.

I managed to get it to run without segfault by either:

* Removing the explicit `#include "main.hpp"` from main source file. Its content is already force-included via the PCH
* Adding `-Xclang -pch-through-header=main.hpp` to the include-what-you-use command-line. This signals to Clang that any include of `main.hpp` is a place-holder for the PCH (this is how MSVC has traditionally done PCH).
* Removing all PCH arguments from the include-what-you-use command line. This causes the main.hpp contents to be included in IWYU analysis

I wish we didn't crash here, but there's a pretty ingrained invariant in IWYU that all files have been seen by the preprocessor.

**Comment by kimgr** [comment]
I think you could go with the middle bullet as a workaround:

> Adding `-Xclang -pch-through-header=main.hpp` to the include-what-you-use command-line

CMake's include-what-you-use integration allows you to pass args in a semicolon-separated list, IIRC.

Overall it would be nice to be more resilient here. There's probably a case to be made that IWYU should reject compilations with PCH enabled, because PCH hides the better part of the dependency graph. But that would push the responsibility onto IWYU drivers that they would need to rewrite compilation arguments, which is even worse...

IWYU could also drop all PCH arguments to avoid using the PCH. But then the program must be able to build with or without PCH.

(Loosely related; my favorite way of setting up PCH was to make them non-intrusive and optional, example here: https://github.com/kimgr/non-intrusive-pch. We used that on a multi-million-line codebase but with a homecooked CMake-like buildsystem generator that knew how to wire everything, so it might be harder with more vanilla systems. The benefit was that we could generate a PCH-less build system for dependency analysis (e.g. with IWYU) or a PCH-ful build system with faster builds.)

**Comment by kimgr** [comment]
> I'm a bit curious about something, though - IWYU usually does not crash when I compile my projects with precompiled headers. Out of the ~60 files being compiled in the projects in which I've experimented with precompiled headers, I get 4 crashes. I haven't been able to figure out any pattern for the crashes, unfortunately.

Just guessing, but maybe most file have explicit `#includes` for their headers, but the failing ones have forgotten to include the equivalent of `core.hpp` and are relying on it coming from the PCH? Aha, no, I see now the failing code is coming from inside the PCH... 

I think maybe the reduced testcase is confused by the fact that the PCH header is called `main.hpp`; `main.cpp` and `main.hpp` form a pair in IWYU and are analyzed together (the "associated header" rule). I think if the pch-generating header was called something else, it would be ignored in analysis, and this wouldn't happen. A bit far-fetched, but could it be that the precompiled headers in the failing project share names with a source file in the project?

**Comment by kimgr** [comment]
Right, that makes sense.

The PCH makes the AST of `widget.hpp` available to the compilation (and IWYU's analysis), but when attempting to record uses/declarations, the preprocessor has not been informed that `widget.hpp` exists, and so all reports will go to /dev/null. Or as in this case, segfault, because we assume all files have been seen.

And thinking more about this, IWYU's entire mission is to associate uses with files, so if the file part of the equation is empty, there's really nothing it can do. Even if we guarded every file lookup against null, the analysis would be entirely lop-sided since any PCH-provided symbol would have no known source.

I'm not sure how to do operate IWYU with PCH...

**Comment by kimgr** [comment]
Cool, I hadn't found that document before. It seems to be missing the include graph information (`PPCallbacks` whenever a file is opened, included, entered, left, etc) -- obviously, since that's no longer necessary -- but I can't quite convince myself if that's crucial information or just how we collect file info currently.

Yeah, modules are just a more well-defined PCH, right? So it should have the same kind of challenges. But modules are also a way to get around the whole `#include` conundrum, so if you're using modules, chances are you don't need IWYU. That said, I don't know enough about modules to understand if it's something you might use incrementally, together with the regular preprocessor. Probably is, which puts us back in this situation.

**Comment by kimgr** [comment]
Latest IWYU no longer accepts invocations with PCH enabled. See https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUFAQ.md#why-doesnt-iwyu-work-with-precompiled-headers-enabled for reason and workaround.
