### ISSUE TITLE
IWYU confuses namespace `assert` with macro `assert`

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1257]
Hi,

Consider the following example:

```cpp
// main.cpp
#include "foo.h"

#define BAR top::assert::bar()
```

```cpp
// foo.h
#include <cassert>

void foo(bool x) 
{
  assert(x);
}

namespace top
{
namespace assert
{
void bar();
}
}
```

Running IWYU:

```
$ include-what-you-use main.cpp  -Xiwyu --verbose=3
main.cpp:3:18: warning: assert is defined in <assert.h>, which isn't directly #included.

main.cpp should add these lines:
#include <assert.h>  // for assert

main.cpp should remove these lines:
- #include "foo.h"  // lines 1-1

The full include-list for main.cpp:
#include <assert.h>  // for assert
```

`main.cpp:3:18` is at:

```
top::assert
     ^
```

So IWYU is confused here.

**Comment by kimgr** [comment]
I don't think your namespace is called what you think it is 🙂.

Try outputting the preprocessed content of your repro using `clang -E` or `clang -save-temps` and you should see how the preprocessor expands your namespace on your platform.

**Comment by carlosgalvezp** [comment]
I thought about that too - `assert` is a macro after all and should in theory be expanded by the preprocessor anywhere where it's used. But that would easily lead to compilation errors, the content of the `assert` macro is not something that can be put in a namespace.

I did run `clang -E` on a simpler example, and indeed `assert` is **not** expanded in the case of the namespace:
https://godbolt.org/z/eWW3fzKe5

Unclear if this is expected or there is some exception to the rule for `assert`.

**Comment by kimgr** [comment]
I didn't know `assert` was guaranteed to be a function-like macro, but it looks like it is.

Debugging this, I came across the following: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_preprocessor.cc#L651.

I never cease to learn new things about IWYU; in this case it seems like it tries to keep track of macros used inside macros, but makes no effort to distinguish between function-like and object-like macros. So yes, this is definitely an IWYU bug!

I can't think of a good solution off-hand.

**Comment by carlosgalvezp** [comment]
Very interesting, thanks for looking into it! Of course the easiest solution for us is to just give the namespace a different name. Perhaps this is a rare edge case not worth the complexity, I'll leave that up to you guys to decide :)

**Comment by kimgr** [comment]
I instinctively treat all C standard library names as reserved in C++ code, because it's so hard to tell what might be a macro vs. an actual symbol in different implementations (Windows is even more exciting, where every Windows API function used to come in three flavors, e.g. `GetObject` that would expand to `GetObjectA` or `GetObjectW` depending on Unicode support. That has caused similar issues for me in the past.).

It would be nice to do something about this, but I'm not sure how to think about it. It seems like IWYU does some kind of eager macro expansion to find definition-side macros even if the outer macro is unused.

**Comment by kimgr** [comment]
I've managed to tell the difference between function-like and object-like macros to suppress the use here: https://github.com/kimgr/include-what-you-use/commit/namespace-assert.

But I'm not sure that helps, entirely, as the use of `top::assert:bar` in the macro should probably force `#include "foo.h"` to be kept.

Let me know what you think. I might write up a testcase and open a PR if it helps at all. You could use `// IWYU pragma: keep` to force `"foo.h"` in place. That doesn't really work today due to the `assert` debacle.

**Comment by carlosgalvezp** [comment]
Thanks for the update! In our case we have migrated from the controversial `assert` namespace to something else to move forward. It feels it's such a narrow edge case we wonder if it's worth the effort fixing - especially if it still requires having a IWYU pragma to keep the include as you say.

So from our point of view we are fine to leave IWYU as-is, but if you believe this might help in other contexts as well then I think it's a great improvement!

**Comment by kimgr** [comment]
Yeah, I think the distinction between function-like and object-like macros has some merit on its own in this context.

The current code just blindly matches identifiers and tries to map them to macros, without considering if the preprocessor will really expand it (e.g. `assert`). Making that work more in line with the real preprocessor would be nice, I think.

**Comment by kimgr** [comment]
Once I started to build out a testcase for this, I found a bunch of edge cases that I'm not sure how to handle. Fun examples:
```
// namespace or macro?
#define ASSERT assert
   -> ASSERT expands to: assert

// function-like invocation only happens after expansion of ASSERT->assert
#define ASSERT2(x) ASSERT(x)
   -> ASSERT2(0) expands to: assert(0)
```

So my heuristic lexing looking for an opening l-paren to determine if the macro denotes a function-like or object-like macro is not enough. I think, as the preprocessor pastes together arbitrary fragments in a way that's eventually consistent. Trying to guess what will or has happened does not seem to be straightforward.

**Comment by kimgr** [comment]
Hey @carlosgalvezp -- I realize I more than 6 months too late, but this stuck with me, and I've poked at it off and on since. Finally got a PR together. I think the rules are:

* IWYU should not worry about nested expansion -- it only cares about which immediate macros are mentioned by the macro being defined 
* IWYU should not worry about delaying analysis until all code has been seen. Once it sees a macro definition, it should evaluate it in the preprocessor context that exists right then and there.
* Clang exposes enough metadata about the preprocessing that we can find out if a token `assert` is a macro, is object-like or function-like, can be expanded, etc.
* So the rule in this case is: if macro is object-like _OR_ it is followed by an opening parenthesis, it's valid to consider it as a macro, otherwise it's something else (e.g. a namespace, like in your case)

All that said, it would be nice if we could also analyze the non-macro components of the macro `BAR`, but that analysis is almost impossible to get right, as it will ultimately depend on in which context `BAR` is expanded.

**Comment by kimgr** [comment]
The `assert` bug is now solved on master. IWYU still can't see that `top`, `assert` and `bar` are provided by `foo.h`, but that's as yet "impossible", and be solved with `// IWYU pragma: export`.

**Comment by carlosgalvezp** [comment]
Amazing job, thanks a lot! :)
