### ISSUE TITLE
include-what-you-use 0.21 behaves strangely with anonymous unions and structs.

### ISSUE THREAD

**Issue by Jhuighuy** [include-what-you-use/include-what-you-use#1336]
Hi!

The latest version of include-what-you-use (0.21, from brew) generates weird output for the following piece of code:
```cpp
#pragma once

template<class T>
class Class {};

template<>
class Class<int> {
  union { // or `struct`, same output
    float x;
    int y;
  };
};
```

Output:
```sh
$ include-what-you-use ./test.hpp

test.hpp should add these lines:

test.hpp should remove these lines:
-   // lines 8-8

The full include-list for test.hpp:
---
```

Everything works fine with version 0.20.

**Comment by bolshakov-a** [comment]
IWYU erroneously handles anonymous `union`s and `struct`s (as well as unnamed ones like `struct { int x; } y;`) like forward declarations after #1232. But the direct reason of the reporting is that a class template explicit specialization is traversed twice. After the second pass, the unnamed/anonymous struct/union declaration is treated as the duplicating forward declaration, and IWYU suggests to remove the duplicate.

The double traversal is removed in the PR #1332. The problem is not reproduced at that branch. Hence, I'm not sure if this issue needs a specific fixing.

**Comment by kimgr** [comment]
PR #1332 is now merged, @Jhuighuy let us know if this still reproduces on master, please.

**Comment by Jhuighuy** [comment]
@kimgr Everything works fine, thanks!
