### ISSUE TITLE
Consider supporting the last two LLVM versions

### ISSUE THREAD

**Issue by firewave** [include-what-you-use/include-what-you-use#1498]
So far the IWYU releases have been aligned with LLVM releases as it is closely tied to to that code.

Unfortunately LLVM updates in distros are usually lacking well behind because of the all the work involved in testing and rebuilding projects which depend on it.

For instance Clang 18 was just released but ArchLinux just updated to Clang 17 so IWYU 0.21 (that is provided via AUR) wasn't available for distros based on that until now. But Clang hasn't hit all downstream distros yet (including mine which is Manjaro Linux) so you cannot use the updated IWYU from AUR until the distro has been updated.

Providing support for the last two LLVM releases would allow IWYU to be updated without updating LLVM as well. That would help to increase the availability of the latest version - at least for rolling/current distros.

I assume the complexity of this would be dependent on what is changed upstream and might range from trivial to extremely messy.

As this project is quite strapped for time I would understand if there is no more room to support this.

**Comment by kimgr** [comment]
How do you envision this would work? Something like one separate mainline branch per LLVM version?

I haven't really thought about it, so I'm genuinely curious.

**Comment by firewave** [comment]
> How do you envision this would work? Something like one separate mainline branch per LLVM version?

As I have no idea how integrated it is with the upstream stuff I cannot say.

I assume the easiest would be to have preprocessor checks based on the LLVM version with CMake looking for a minimum LLVM version instead of a fixed one.

I just thought it might be worth pointing out since I am keep having a real hard time getting a recent IWYU on my local systems.

**Comment by kimgr** [comment]
It's pretty integrated :) --

* Clang exposes callbacks from the preprocessor that we listen to and record the include graph
* Clang has an AST visitor that we both customize traversal of and implement callbacks from to analyze the AST
* The Clang driver is a framework that we use and customize
* We use LLVM support libraries for basic algorithms, data structures and portability

The kinds of changes we typically see are:

* Some API changed slightly and usage needs to be adjusted to compile (e.g. https://github.com/include-what-you-use/include-what-you-use/commit/f27fafa378a70b975aeaa9a1428b275a1edcfe5a)
* A core type is being slowly phased out in favor of another (e.g. https://github.com/include-what-you-use/include-what-you-use/commit/b61a8feb861657947f82421eead59b20b44925df)
* The AST is fundamentally changed in a way that breaks IWYU (e.g. https://github.com/include-what-you-use/include-what-you-use/compare/941fc197852d9f6ff82f4f0deafe97a08d7affd8...18a331be381e4550d691e562d00db08da493403c)
* Build requirements change (e.g. https://github.com/include-what-you-use/include-what-you-use/commit/e94a78b3a569197e124f9dd1d5068da46ebb0031)

It may be possible to maintain a cross-compatible IWYU, but like you said, we only have limited time. I personally work on IWYU because I think it's fun and rewarding. Trying to keep compatibility across major LLVM versions would definitely take most of the fun out of it. IWYU is more of a research project. I don't have skills, resources or interest to productize it much beyond its current state.

**Comment by firewave** [comment]
Fair enough. It's what I expected but I still thought it might be worth to raise the issue.

I also guess the issues I am having are mainly resolved when updates to Compiler Explorer can be finally done on release (see #1358). I totally forgot about that ...

**Comment by firewave** [comment]
Thanks for looking into this!
