### ISSUE TITLE
Release debian packages if possible

### ISSUE THREAD

**Issue by eyalroz** [include-what-you-use/include-what-you-use#1587]
It would be nice if releases could also include a Debian-compatible `.deb` package. I realize it's not your responsibility, but - it should definitely be part of Debian-based distributions.

**Comment by firewave** [comment]
There are official Debian packages:
https://debian.pkgs.org/10/debian-main-amd64/iwyu_7.0-3_amd64.deb.html
https://debian.pkgs.org/11/debian-main-amd64/iwyu_8.15-2_amd64.deb.html
https://debian.pkgs.org/12/debian-main-amd64/iwyu_8.18-2_amd64.deb.html
https://debian.pkgs.org/sid/debian-main-amd64/iwyu_8.22-1_amd64.deb.html

The latest version might not be available until the latest LLVM is available because they are tightly coupled.

**Comment by eyalroz** [comment]
> The latest version might not be available until the latest LLVM is available because they are tightly coupled.

Yes, somehow it's not available on trixie - and I assumed it wasn't available, period. Sorry.
