### ISSUE TITLE
iwyu removes differently named headers with declarations even despite  -Wmissing-declarations -Werror

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/include-what-you-use#179]
Originally reported on Google Code with ID 179

```
Issue is present with C code. In project I participate gcc options -Wmissing-declarations
-Werror are required, also declarations in header files can be split into public and
those available only inside the repository (private), with whose iwyu has a problem.

Problem can be reproduced on attached files. iwyu gives output:
$ iwyu StringTest.c -Wmissing-declarations -Werror
StringTest.c should add these lines:

StringTest.c should remove these lines:
- #include "StringTestPrivate.h"  // lines 1-1

The full include-list for StringTest.c:
#include <stdlib.h>                     // for calloc
#include <string.h>                     // for memcpy

---

Clearly applying such fix would lead to:
$ gcc StringTest.c -Wmissing-declarations -Werror
StringTest.c:6:46: error: no previous declaration for ‘memcpytest’ [-Werror=missing-declarations]
 __attribute__ ((visibility ("hidden"))) int *memcpytest(int **var, int **val) {
                                              ^
cc1: all warnings being treated as errors

With these flags I expect iwyu to include headers providing required declarations regardless
of where they are.

Tested on Ubuntu 14.04
$ iwyu --version
include-what-you-use 0.3 (590) based on clang version 3.5.0 (tags/RELEASE_350/final)
$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

```

Reported by `mrzyglocki.marcin` on 2015-03-03 13:16:30

<hr>
- _Attachment: [StringTest.c](https://storage.googleapis.com/google-code-attachments/include-what-you-use/issue-179/comment-0/StringTest.c)_
- _Attachment: [StringTestPrivate.h](https://storage.googleapis.com/google-code-attachments/include-what-you-use/issue-179/comment-0/StringTestPrivate.h)_

**Comment by bungeman** [comment]
A relevant llvm issue: https://llvm.org/bugs/show_bug.cgi?id=16286
The gcc documentation for 'missing-declarations': https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmissing-declarations-558
See also 'missing-prototypes' in the gcc documentation.

I believe that IWYU should generally see a definition of a global function (and probably a global variable) as a use of any previous declaration; and should in fact suggest directly including a header with the declaration should one be found. From a user perspective it's easy to think that IWYU already does this, because of the 'special' of associated headers.

**Comment by bungeman** [comment]
I'm attaching a patch which does what was requested. I wrote this for similar reasons, IWYU was trying to remove a bunch of includes which were wanted. Note that this does so unconditionally (doesn't look at flags). Also note that while this adds a test to verify, this breaks all sorts of current test expectations (if it didn't I'd propose it as a pull request). One direct issue is that this considers *all* previous declarations as used by the definition when we really only need one. The more general issue is that this almost completely turns the philosophy of IWYU 'use' on its head, which I think would generally be a good thing (and would allow removing the 'associated header' hack). In other words this is part of a much larger tension in what is expected than I think I can reasonably propose a solution to. While this tension exists, this might be a reasonable work around.

[0001-Definition-of-global-is-use-of-declaration.patch.txt](https://github.com/include-what-you-use/include-what-you-use/files/38154/0001-Definition-of-global-is-use-of-declaration.patch.txt)

**Comment by kimgr** [comment]
I had completely missed your comment from July, sorry about that!

Thanks for this analysis, it makes good sense in theory. I can't quite see through the effects in practice.

We'll probably still need to keep track of 'associated headers' to be able to co-analyze and handle spill between a component's .h and .cpp, or would that also sort itself out, you think?

I'll have to apply this and see if I can understand what kind of broad effects it has on the current test suite. I have some other stuff in the air, but I'll try to get back to you soon.

**Comment by kimgr** [comment]
I just checked out and tested your patch on Windows. For some reason your new `def_is_use` test fails, along with some other tests:

    FAIL: runTest (__main__.def_is_use)
    FAIL: runTest (__main__.header_near)
    FAIL: runTest (__main__.lateparsed_template)
    FAIL: runTest (__main__.redecls)

(edited to remove expected failures on Windows/MSVC.) Does this match your test results?

> One direct issue is that this considers all previous declarations as used by
> the definition when we really only need one.

This sounds a little aggressive. Doesn't it mean that if I'm both forward-declaring and including a declaration, IWYU will want to keep both? Or does it only apply to the definition-is-use case?

> The more general issue is that this almost completely turns the philosophy of IWYU 'use' on its head

Given the small number of test failures I see, it can't be that bad :-)

In exactly what sense to you mean that the philosophy is overturned? Because *any* declaration for a use is no longer sufficient?

**Comment by kimgr** [comment]
I just came back to this.

The `def_is_use` failure appears to be benign (for some value thereof); your patch had two files unused in the test. With these removed, the test passes.

The logic in `VisitFunctionDecl` seems slightly wrong --

* I think you use `isGlobal` to see if it's a free function, presumably because a definition of a non-free function will always include the enclosing class name. That doesn't appear to be what `isGlobal` does -- it returns true for static methods, among other things. I replaced it with `!isa<CXXMethodDecl>()` and that appears to work better (fewer tests failure)
* We should always enter a forward-declare context regardless of whether it's a free function or not, so the if/else needs to be slightly different:
```
    if (definition) {
      if (!cxx_method) {
        // report uses of all redecls
      }
    } else {
       // enter forward-declare context
    }
```
with that fixed, only the `redecls` test case fails, as expected.

Now, I wonder if this could be made less radical :-)

I guess the typical case is some header containing a declaration, and we want to make sure  a definition in harmony with it.

Why is it not enough to say any redeclaration is fine? If I have a decl in the same file as the definition, it seems to me I'm not so interested in the decl in the header. If there are multiple headers with redecls, isn't any one of them enough?

**Comment by EdSchouten** [comment]
I'm currently trying to use IWYU to sanitise all of the code of cloudlibc, a C library:

https://github.com/NuxiNL/cloudlibc

This is affecting me in a couple of places, such as `<libgen.h>` and `<ctype.h>`, where IWYU considers it unnecessary to leave those includes around in the source files that implement the functions defined within.

I'd really love to see this get fixed, as it would help me a lot. Is there anything I can do to help out?

**Comment by kimgr** [comment]
Thanks for the added detail. I thought some more about this today, and I think the challenge is to determine what kind of behavior we want -- when a definition is found, should all visible (re-)declarations of that definition be marked used? If not, which ones? I can't think of a way to select a canonical declaration off the top of my head.

**Comment by EdSchouten** [comment]
That is a pretty good question.

I think it would be _sufficient_ if it was dealt similarly to what we're discussing in #483. As in, only retaining a single include using minimal set cover, while respecting the existing input.

That said, requiring that all declarations are marked as used is actually pretty smart, Kim. It acts as a safety belt that if the function's prototype would get changed later on, none of the header files go out of sync accidentally. What do you think?
