### ISSUE TITLE
Test script doesn't look in the PWD for include-what-you-use binary.

### ISSUE THREAD

**Issue by Earnestly** [include-what-you-use/include-what-you-use#216]
Sorry if this is a duplicate but after having built `include-what-you-use` I attempted to run `./run_iwyu_tests.py` with the following error:

```
earnest % ./run_iwyu_tests.py
Traceback (most recent call last):
  File "./run_iwyu_tests.py", line 25, in <module>
    import iwyu_test_util
  File "/home/earnest/build/lab/include-what-you-use-git/src/include-what-you-use/iwyu_test_util.py", line 97, in <module>
    _IWYU_PATH = _GetIwyuPath(_IWYU_PATHS + _SYSTEM_PATHS)
  File "/home/earnest/build/lab/include-what-you-use-git/src/include-what-you-use/iwyu_test_util.py", line 76, in _GetIwyuPath
    raise IOError('Failed to locate IWYU.\nSearched\n %s' % '\n '.join(iwyu_paths))
IOError: Failed to locate IWYU.
Searched
 ../../../../Debug+Asserts/bin
 ../../../../Release+Asserts/bin
 ../../../../Release/bin
 ../../../../build/Debug+Asserts/bin
 ../../../../build/Release+Asserts/bin
 ../../../../build/Release/bin
 ../../../../../build/Debug+Asserts/bin
 ../../../../../build/Release+Asserts/bin
 ../../../../../build/Release/bin
 ../../../../../build/bin/Debug
 ../../../../../build/bin/Release
 ../../../../../build/bin/MinSizeRel
 ../../../../../build/bin/RelWithDebInfo
 /home/earnest/.local/bin
 /usr/local/sbin
 /usr/local/bin
 /usr/bin
 /usr/bin/site_perl
 /usr/bin/vendor_perl
 /usr/bin/core_perl
```

It seems the script is not looking for the `include-what-you-use` binary that was just created and currently resides in the same working directory as `run_iwyu_tests`.

What am I doing wrong?

**Comment by kimgr** [comment]
Those paths were hard-coded years ago, and I don't think they work reliably.

What I usually do is add the directory to which `include-what-you-use` is built to my `PATH` in the shell I use for IWYU development. I patched the `run_iwyu_tests.py` script to search the `PATH`, that's why the rest of your `PATH` shows up in the list.

**Comment by Earnestly** [comment]
This is for a package, not for development of the project.  Why not patch the script to include the current working directory as well?

I'd much rather have upstream define the code than tamper with it downstream.

**Comment by kimgr** [comment]
It's just a surprise to me how `run_iwyu_tests.py` ends up anywhere near the executable, I guess. How is the package built?

I'm not fundamentally opposed to including `$PWD`, it just seems weird to me that it would be useful.

**Comment by Earnestly** [comment]
It is not built in a `build` directory.  As this is a package and is a oneshot process, it just builds in the same directory as the `CMakeLists.txt`

**Comment by kimgr** [comment]
From my point of view, `$PWD` is just as arbitrary as any of the other hard-coded paths (and they really shouldn't be there.) I don't see how

    PATH=.:$PATH run_iwyu_tests.py

is any less reproducible than having `.` in the search path.

Just to be clear, I'm not arguing to be difficult, I'm just trying to find a model that works more generally. I don't think a lot of people have their executable in `.`.

It seems to me it would make sense to be able to tell `run_iwyu_tests.py` which IWYU executable to use for testing, e.g.

    $ run_iwyu_tests.py -- ./include-what-you-use

I want the '--' separator there because you can currently tell the test runner which test case(s) to run, so we'd need to separate that from the executable.

**Comment by kimgr** [comment]
Oh yeah, and I wanted to ping @daveisfera about this, since he's doing packaging for Fedora. If this is a recurring theme in packaging, that might win me over :-)

**Comment by Earnestly** [comment]
This isn't about hardcoding a bunch of locations--that is a mistake (so is (ab)using `PATH` like this)--it's about making a very typical and correct assumption that resources are available in the processes' cwd.  Even if you made a symlink into a build directory it would still work.

The alternative would of course to be providing an option to set the directory where tests are available and of course the binary with which to do it.

**Comment by kimgr** [comment]
I agree with you that relying on `PATH` isn't such a great idea, but it turns out to be really convenient for development (it lets me build IWYU and experiment with it from the command-line, and then run the tests knowing they will use the same one.) And it works well across platforms.

I don't see that same convenience/flexibility combo with any of your suggestions so far.

The best I can offer you is probably a switch for `run_iwyu_tests.py` to say where the executable is. That would make sense to me anyway; as I said, searching the PATH is mostly for convenience.

I'll look into this, but it might be a couple of days, I have some other engagements.

**Comment by daveisfera** [comment]
For the Fedora packaging, PWD is added to PATH. That's not a big deal from
my perspective, so I'm fine either way on this one is fine by me.

**Comment by Earnestly** [comment]
So hacks it is.

**Comment by daveisfera** [comment]
Ya, but one person's "hack" is another's "way it's supposed to be". It's
fairly common in the Linux world to not consider PWD by default, because
then the user can include it if they want by adding . to PATH but it's not
forced onto everyone.

**Comment by kimgr** [comment]
Please find hack in PR #218, let me know if that works for you.
