### ISSUE TITLE
Readme declares alpha as of 2011...

### ISSUE THREAD

**Issue by MatthiasKauer** [include-what-you-use/include-what-you-use#259]
Hi,
just passing through here.
Readme declares that this is alpha software as of 2011. That's quite a while ago.
Have things changed or does it still require extreme caution?

Kind regards,
Matthias

**Comment by kimgr** [comment]
I wouldn't say "extreme caution", but IWYU definitely still makes mistakes.

My company is using it on a ~2MLOC code base and we can use 95% of the suggestions as reported. We make manual changes based on IWYU's input, and lean on the compiler or our judgment to make sure nothing breaks (e.g. `#define`-dependent or order-dependent includes.)

I'm not sure what that says about our alpha status, but there are still several problems we haven't identified a systematic solution for, so I guess it's pretty fair.

**Comment by vsapsai** [comment]
We are trying to keep IWYU stable. For example, won't change command line arguments willy-nilly. So in this regard you should be safe.

And as Kim mentioned, there are a few remaining important problems, that's why I think we cannot declare 1.0 version.

Overall, it is OK to use IWYU but you need to verify recommendations don't have mistakes.

**Comment by MatthiasKauer** [comment]
Thanks for the clarification. That's a much better state than I would have expected from the Readme.
