### ISSUE TITLE
iwyu cmake process assumes being checked out via github

### ISSUE THREAD

**Issue by JVApen** [include-what-you-use/include-what-you-use#262]
If you checkout iwyu via subversion (svn co https://github.com/include-what-you-use/include-what-you-use/trunk include-what-you-use), and afterwards configure your build via cmake, you get the following error: 

-- IWYU in-tree configuration
fatal: Not a git repository (or any of the parent directories): .git

Note: My machine has a git-client installed, it just isn't used to checkout iwyu, as I do an in-tree build and my llvm checkout was done via subversion.

**Comment by kimgr** [comment]
I use SVN for LLVM/Clang but pull the IWYU Git repo out into it, that works fine. We rely on Git to build our version information, and supporting SVN again is at least not on my radar.

If you can come up with a non-intrusive patch that generates empty/nonsense version info in the absence of Git, I'd be happy to take it!

**Comment by JVApen** [comment]
Tnx a lot! If I understand you correctly, I get a fatal error, though everything works fine.
Any way you could get rid of the 'fatal'?

**Comment by kimgr** [comment]
I don't know if that's the case, I meant to say that we only really support Git checkouts.

So there are two viable options:

1) Check out a Git clone instead of using Subversion. It works fine to combine an IWYU Git clone with an LLVM/Clang SVN checkout

2) Patch IWYU not to require Git. If the changes required are not entirely crazy, we can integrate them into IWYU mainline

Supporting SVN checkouts is not a priority for me.

**Comment by JVApen** [comment]
This resolves the 'fatal' error, sorry I'm not good in using git yet :/
Can you check if it keeps working for actual git checkouts?

[noGit.diff.zip](https://github.com/include-what-you-use/include-what-you-use/files/120675/noGit.diff.zip)

**Comment by kimgr** [comment]
Thanks, I posted PR #263 based on your patch. It works both with and without `.git` present.
