### ISSUE TITLE
IWYU ignores default const argument

### ISSUE THREAD

**Issue by salty-horse** [include-what-you-use/include-what-you-use#291]
Using latest git b70df35a236b0f69939573a40484c151414d410f

Given the following files:

#### a.cpp
```c++
#include "c.h"
#include "b.h"
void foo() {
	test();
}
```
#### b.h
```c++
int test(int arg = DEFAULT_VALUE);
```
#### c.h
```c++
const unsigned int DEFAULT_VALUE = 1;
```

IWYU recommends throwing c.h away, leaving `DEFAULT_VALUE` undefined:
```
a.cpp should add these lines:

a.cpp should remove these lines:
- #include "c.h"  // lines 1-1

The full include-list for a.cpp:
#include "b.h"  // for test
---
```

**Comment by vsapsai** [comment]
It is correct recommendation, as far as I can tell. If you add `-Xiwyu --check_also=b.h` in command line, IWYU will recommend for `b.h` to add
```c++
#include "c.h"  // for DEFAULT_VALUE
```

And I think it's correct because `b.h` uses `DEFAULT_VALUE` so it should include file with `DEFAULT_VALUE`.

Unfortunately, currently IWYU by default doesn't analyse `.h` files without corresponding `.cc/.cpp` files so you need to trigger analysis for such files with `-Xiwyu --check_also`.

**Comment by salty-horse** [comment]
Missed that. Thanks for the clarification!
