### ISSUE TITLE
Replacing Each with range loops

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#310]
Looks like Each is relic of time when code was built in C++98/03. This is definitely obsolete when LLVM/Clang switched to C++11.

**Comment by kimgr** [comment]
I support this. We usually change them when we make related changes, but it's going so slow that I would prefer to make a one-time conversion to simplify the code. @vsapsai, are you OK with that?

**Comment by vsapsai** [comment]
I don't see value in doing this. But if people think it is useful, sure, go ahead.

**Comment by EugeneZelenko** [comment]
Code which uses standard language features are more comprehensive, especially for outsiders.

**Comment by kimgr** [comment]
See PR #330

**Comment by vsapsai** [comment]
@EugeneZelenko, @kimgr, I want to apologize for my behavior. You provided valuable feedback and my snarky comment was inappropriate. I've been on the other side and now better understand  negative impact of using custom solutions instead of standard language features. Thanks for sharing your experience and teaching me something new.

**Comment by kimgr** [comment]
@vsapsai: it didn't come out as snarky at all, no offense taken!

**Comment by EugeneZelenko** [comment]
@vsapsai: I didn't see any offense in your comment. Sure, time is limited, so there are may be more important problems then code cleanups.

@kimgr: Thank you for code refactoring!

**Comment by vsapsai** [comment]
Oh, thanks guys for your support.
