### ISSUE TITLE
LLVM/CLang 3.9 branch

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#343]
LLVM/CLang 3.9 branch was created yesterday. I think will be good idea to pull pending changes when approved and create IWYU branch.

**Comment by kimgr** [comment]
Usually the way we do this is create the branch as soon as Clang/LLVM HEAD introduce something that makes IWYU incompatible. Up until that point the branch is just waste, incurring a cost for merging commits between two otherwise identical branches.

But otherwise I agree with you, it would be nice to close the loop on a lot of the pending PRs so we're ready to release soon after LLVM/Clang.

**Comment by kimgr** [comment]
A new warning showed up when I synced master today, so I pushed a branch for 3.9:
https://github.com/include-what-you-use/include-what-you-use/tree/clang_3.9

Warning soon to be fixed on master.

**Comment by kimgr** [comment]
Fixed warning in 4a57380c21fdedc0362fc30311932f704b48d107.

**Comment by vsapsai** [comment]
As branch is created, closing the issue. For further release planning we can use #359.
