### ISSUE TITLE
More friendly instructions?

### ISSUE THREAD

**Issue by revolter** [include-what-you-use/include-what-you-use#348]
I have no single clue of how to "install" this software.

First of all, I don't know what build configuration I should use.
Secondly, I don't understand the difference between building and installing this software. Does it have an installer?
And I don't understand what `/path/to/llvm/Debug+Asserts/bin/include-what-you-use` represent. Does it represent our project's source code? If yes, why is there mentioned `include-what-you-use`?

**Comment by vsapsai** [comment]
The quickest way to try `include-what-you-use` is to download prebuilt binaries for popular systems from http://include-what-you-use.org/downloads/ What operating system are you using? Does it have binaries on aforementioned page?

There is no installer but there is `install` target which [copies built binary together with a few supporting files](https://github.com/include-what-you-use/include-what-you-use/blob/master/CMakeLists.txt#L181-L186) to defined location. If you are just starting it will be easier just to build without installation.

`/path/to/llvm/Debug+Asserts/bin/include-what-you-use` represents path to `include-what-you-use` binary on your system. How to invoke IWYU depends on your project's build system. Are you using Makefiles or CMake or something else?

**Comment by revolter** [comment]
Thank you very much for the explanation!

I searched the website for prebuilt binaries downloads but couldn't find that link. Probably because I was searching for "Downloads" and not "All downloads". I know it sounds dumb, but as we know, [users don't read][1].

I am using OS X. I was trying to use this for [DB Browser for SQLite][2] project, which uses `QMake`, as far as I understood. I have little knowledge of build systems like make and such. Can you provide me some guidance to running it against DB4S?

Also, do you think that your comment can find a place in the `README`? As I find it quite enlightening and helpful.

  [1]: http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html
  [2]: https://github.com/sqlitebrowser/sqlitebrowser

**Comment by vsapsai** [comment]
Integrating include-what-you-use with build process is basically invoking it instead of compiler. Based on [Qt documentation](http://doc.qt.io/qt-5/qmake-variable-reference.html#qmake-cxx), you need to override `QMAKE_CXX`. Here is also [relevant Stack Overflow question](http://stackoverflow.com/questions/7964566/adding-different-compiler-to-qt). Don't know if full path will work or you need to add include-what-you-use to PATH and use only file name. My experiments on Windows failed (I have Qt installed only there), despite my attempts Qt was always invoking MS Visual Studio compiler. Hope you have better luck on Mac OS X.

The point about `README` is valid. It might be better to move instructions where to get prebuilt binaries before instructions how to build.

**Comment by dismine** [comment]
@revolter current advice from documentation works for qmake as well.

> Configure a tree for a clang build and then run make with the following options: -j1 -k CXX=/path_to_bin/include-what-you-use. I’m not certain if the -j1 is necessary, but since IWYU spits out lots of output, it seemed wise. The -k tells make to keep building even after errors; for some reason, IWYU triggers compilation failure on every file it looks at. 

So, first run qmake with the right spec (see right spec name because i am not sure about my example)
`qmake -spec macx-clang`
Then run make
`make -j1 -k CXX=/path_to_bin/include-what-you-use`
I also recommend save output to log file.
`make -j1 -k CXX=/path_to_bin/include-what-you-use 1>./log.txt`

**Comment by revolter** [comment]
Thank you for your comments. I understood it better, but still don't think I got it to work. After running the `make` command, it outputs multiple errors like:

```
/Users/revolt/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h:39:12: fatal error:
      'cstddef' file not found
#  include <cstddef>
           ^
```

and after running the `fix_includes`, I get the message `IWYU edited 0 files on your behalf.`, even though I intentionally added one include that I am sure was not used. If you have time to help me, please do, if not, you are free to close this issue, as it's not a critical one. I was just trying to help DB4S fix the potentially include issues, but I can do that manually though.

**Comment by dismine** [comment]
@revolter , are you sure your code is not broken? Can you build it with regular make? Today i had successful experience checking Qt5 based project.

**Comment by revolter** [comment]
I'm only using `Qt Creator` for building the project. The code is not broken though, I checked out the HEAD where Travis built it ok.

**Comment by dismine** [comment]
Look, i can't say for sure what is wrong in your case. Here how i run check:
`make -j1 -k CXX="/home/osboxes/Downloads/include-what-you-use/bin/include-what-you-use -Xiwyu --transitive_includes_only -Xiwyu --mapping_file=/home/osboxes/Downloads/include-what-you-use/mappings/qt5_4.imp -Xiwyu --mapping_file=/home/osboxes/CAD/Valentina_0.5.x/valentina/build/dismine.imp" 1>./log.txt 2>./err.txt`

**dismine.imp** contains mappings that fix problem with wrong header names. Original mapping qt5_4.imp should theoretically cover it, but doesn't do it. 

Before run _fix_includes.py_ i fixed path to source files because it were broken.
`python /home/osboxes/Downloads/include-what-you-use/bin/fix_includes.py < err.txt`

And yes, i used version 0.6 available on website.

**Comment by revolter** [comment]
With your full commands, it worked. Though I didn't see `mapping_file` anywhere in the `README`, so I didn't know I need to use it.

**Comment by dismine** [comment]
Believe me if you use Qt better to do it. Read this page https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md.

Be careful about this part:

> #You'll get these and probably have to ignore them. I'm not sure how to deal with these.
> #include "QtCore/qtypetraits.h"  // for remove_reference<>::type
> #include "QtCore/qsharedpointer_impl.h"            // for swap
> #include "QtCore/qatomic_msvc.h"

And in my case ignore mean to remove these include if they are present.

**Comment by kimgr** [comment]
Is there anything we can/should do for this bug?

**Comment by revolter** [comment]
I can't remember, but it looked it solved my problem back then 😆 I'll close this now, thanks for the help!
