### ISSUE TITLE
Release to match LLVM/Clang 3.9

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#359]
LLVM/Clang 3.9.0 was released today. I think will be good idea to release IWYU too.

**Comment by vsapsai** [comment]
OK, from my side for release I want to
* finish fix for issue [#247: Include C++ header directory in binary release](https://github.com/include-what-you-use/include-what-you-use/issues/247), current WIP is [in my fork](https://github.com/vsapsai/include-what-you-use/commit/216e6f36caebff3a4394c4845f8581e0666711df);
* fix [#346: Assert in iwyu.cc on Clang code](https://github.com/include-what-you-use/include-what-you-use/issues/346).

But these aren't hard requirements, just things nice to have. So if it takes time to finish them it is better to release without those fixes.

And I'd like to include [#350: Improve macro use-attribution heuristics](https://github.com/include-what-you-use/include-what-you-use/pull/350) but I'm not sure how close it is to completion. To me it looked pretty much ready.

**Comment by kimgr** [comment]
Yes, I'd also like to include #350, it's a strict improvement over what we have.

Unfortunately, #358 shows that it doesn't work for nested macros. I had a whole day to work on it recently (which hardly ever happens), but didn't figure it out. Ideally it would be nice to solve this as well for 0.7, but I wouldn't block the release on it if it takes too long. It was already broken in 0.6.

**Comment by EugeneZelenko** [comment]
If Clang API was not changed since [July 29](https://github.com/include-what-you-use/include-what-you-use/commit/4a57380c21fdedc0362fc30311932f704b48d107), I think will be good idea just to delete clang_3.9 branch and recreate it from master with this change.

**Comment by brad0** [comment]
Please put out a new release. Very much looking forward to this so we can update our LLVM port / package for OpenBSD.

**Comment by kimgr** [comment]
@EugeneZelenko: There were two API changes since the branch point.

I'll cherry-pick the following now:

9ab7286 On macOS search for libc++ headers in command-line tools and Xcode (fix issue #247).
bb61a50 Terminology: as-typed -> as-written
0097735 Merge two forward-decls into the same namespace
2163156 Use range-for loops in YAML parsing
25e3f93 Use emplace_back
7e7428a Remove unused using decls
dcbc9cc More inconsistent parameter names (to be squashed)
dbceeb3 Fix inconsistent parameter names
94949d0 Add comments for closing namespace brace
aa2dd1b Whitespace changes from clang-(tidy|format)
d0be569 Fix bug in source extension detection
2205f1a Add minimal mappings for libc++
9c432a9 Recognize nested classes in friend declarations
f09dba6 Clean up output from test runner
04f1c92 Handle internal headers guarded by macro and x-macros (fix issue #109).
2f826a3 Don't require grep to run tests.
0cfdff2 Increase log level for macro lexer
2141bde Fix #332: Classify pointer arithmetic as a full use

I'd like to keep working on the macro expansion logic, but I realistically won't have time to do it, so let's save that for 0.8.

**Comment by kimgr** [comment]
Actually, I think it will be easier to reboot the `clang_3.9` branch from scratch, and revert the two LLVM-syncing commits. I'll do that and force-push a new `clang_3.9`.

**Comment by vsapsai** [comment]
OK. I think we can start preparing release notes. My attempt to fix #346 is not close to completion and shouldn't block the release.

**Comment by brad0** [comment]
Any update on this?

**Comment by kimgr** [comment]
Sorry, life got in the way at my end. I wrote up some release notes and posted a web-site PR here:
https://github.com/include-what-you-use/include-what-you-use.org/pull/5

I think I'd like to merge PR #350 as well, @vsapsai, can you take a look? There's more work to be done here, but I think we can take this as an incremental improvement if it doesn't look entirely broken to you.

**Comment by vsapsai** [comment]
@kimgr, I plan to build macOS and Ubuntu binaries till the end of this week and/or on weekend. Do you think we'll be able to release IWYU next week? Can you please build binaries for Windows and FreeBSD?

**Comment by kimgr** [comment]
@vsapsai, great! I have a day alone this weekend, so I can definitely build the binaries and upload them. Let's sync up on e-mail during the weekend.

**Comment by vsapsai** [comment]
With Kim's help uploaded IWYU 0.7 to http://include-what-you-use.org

**Comment by EugeneZelenko** [comment]
I think will be good idea to create release tarball on GitHub too.

**Comment by vsapsai** [comment]
Thanks for reminder, created tag `clang_3.9`.

**Comment by EugeneZelenko** [comment]
Thank you for help!
