### ISSUE TITLE
Typedefs of template arguments aren't required anywhere

### ISSUE THREAD

**Issue by kimgr** [include-what-you-use/include-what-you-use#431]
While investigating #412, I realized that IWYU's current handling of typedefs of template arguments must be broken.

Consider this test case:

```c++
// class.h
class Class {};

// typedef_tpl.cc
#include "class.h"

template<class T>
class Container {
 public:
  // Should not be an iwyu violation for T inside the template...
  typedef T value_type;
};

void Instantiations() {
  // ... but when this typedef is used, surely the underlying type must be
  // required?
  Container<Class>::value_type vt;
}
```

Running IWYU on typedef_tpl.cc gives the following:
```
$ include-what-you-use typedef_tpl.cc

typedef_tpl.cc should add these lines:
class Class;

typedef_tpl.cc should remove these lines:
- #include "class.h"  // lines 1-1

The full include-list for typedef_tpl.cc:
class Class;
---
```

So it suggests that Class should be forward-declared instead of included. When I do that, on the other hand:
```
$ include-what-you-use typedef_tpl.cc
typedef_tpl.cc:14:32: error: variable has incomplete type 'Container<Class>::value_type' (aka 'Class')
  Container<Class>::value_type vt;
                               ^
typedef_tpl.cc:2:7: note: forward declaration of 'Class'
class Class;
      ^

(typedef_tpl.cc has correct #includes/fwd-decls)
```

IWYU produces broken code in this case. I haven't isolated where this happens yet, but I thought I'd write it down while I have it repro:ed.

**Comment by jcageman** [comment]
Just as an addition to this, i noticed in our own source code that we had something similar, although a bit more difficult. Just to ensure this is also taken into account in a future fix.

```
template<T>
void Instantiations() {
  typedef SValueTraits<T>::TValueType vt;
}

valuetype.h

template<>
struct SValueTraits<CType>
{
  typedef CValueType TValueType;
}

```

As you can see, to know the outcome of this typedef we have a header which defines the SValueTraits<T>::TValueType specialization. Hence, when you use Instantations for a specific type T you have to include the header which defines the SValueTraits<T>::TValueType. Currently we add this include at the calling side and not in the the file that implements void Instantiations(). I currently manually fix these errors, since they don't occur a lot.

**Comment by kimgr** [comment]
Thanks for the report! Does this happen only for nested typedefs, or is it a general problem with template specializations? If the latter, we may want to split it out into a new bug.

**Comment by jcageman** [comment]
I am not sure about the latter to be honest, i did at least not encounter issues with template specializations. I would suggest to first analyze the typedef issue and from there we can conclude if we have to split this issue.
