### ISSUE TITLE
Please return different exit codes

### ISSUE THREAD

**Issue by LebedevRI** [include-what-you-use/include-what-you-use#440]
A followup for #157
Looking at https://github.com/include-what-you-use/include-what-you-use/blob/13cd94804b140b06e0a58d2f949f13135a29e8d2/iwyu.cc#L3948-L3951, i'm guessing this was never actually merged, or was reverted.

It would be really nice if IWYU could return zero if it did not suggest anything, and anything else (e.g. 1) if there are any suggestions.
When used with https://cmake.org/cmake/help/v3.3/prop_tgt/LANG_INCLUDE_WHAT_YOU_USE.html, this would allow for compilation to be stopped if there are any issues.
This already works quite nicely with clang-tidy...

**Comment by vsapsai** [comment]
I believe IWYU [exits with value 2 if there are no suggestions](https://github.com/include-what-you-use/include-what-you-use/blob/db2391c979ddd59e297f460011eb348cdcefd18f/iwyu.cc#L3525-L3526). Isn't it working for you?

**Comment by LebedevRI** [comment]
`2`, exactly.
> It would be really nice if IWYU could return zero if it did not suggest anything, and anything else (e.g. 1) if there are any suggestions.

**Comment by kimgr** [comment]
I'm beginning to think IWYU's original design, using a failure exit code to allow repeated re-analysis with `make -k`, has outlived its usefulness (see https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/InstructionsForUsers.md#plugging-into-make)

Does someone with more GNU Make chops see a way to simulate the above behavior without playing with the exit codes?

**Comment by Bu11etmagnet** [comment]
I think that integration with the build system is desirable (not just make; it would work with `ninja -k0`). It is the easiest way to run iwyu with the necessary flags on all the sources of a project.

I see several possibilities:

- Always return a non-zero exit code; e.g. 1 for no suggestion and 2 if there were any suggestions.
- Return non-zero by default; return 0 or 1 if a certain command-line argument is supplied (e.g.  --descriptive-exit-codes). 

The we can have our cake and eat it too.

**Comment by LebedevRI** [comment]
> It is the easiest way to run iwyu with the necessary flags on all the sources of a project.

Are you aware that it is possible to natively run IWYU from any cmake-generated project? (see link in first comment). I wonder how much people actually use it the recommended way (by replacing CC before calling make). I'm not sure this even works with auto-generated makefiles

**Comment by kimgr** [comment]
> Are you aware that it is possible to natively run IWYU from any cmake-generated project?

This is now documented here: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/InstructionsForUsers.md#using-with-cmake. But it only works if you already have a CMake system, obviously.

> I wonder how much people actually use it the recommended way (by replacing CC before calling make). 

Internally at my company, we don't. Our build system is pretty homogenous, so we use a brute-force analysis mode where we pass the union of all compiler options to IWYU for all files (headers too). We then pick up the analysis results and generate a web site. It's in-elegant, but it works. 

> I'm not sure this even works with auto-generated makefiles

That depends on the generator. CMake's generated systems have the compiler path hard-coded in, but you could envision a generator that produced `$CC` and `$CXX` for downstream customization.

**Comment by vsapsai** [comment]
I think it is still valuable to plug IWYU in as compiler with `$CC` and `$CXX`. I expect build tools to allow customizing used compiler so I'd keep this integration path open.

What I would be more comfortable with is 2 binaries. One `include-what-you-use-inject` that works like current IWYU and can be substituted instead of compiler. Another binary is `include-what-you-use-compilation-db` that works with compilation DB natively and can return 0 if there are no recommendations. I haven't really thought through this approach so it might be completely wrong. But I think this should satisfy most users' needs.

Another point is that current exit codes are public interface and we need to think twice before changing it as other people can depend on current implementation. It also means that the change isn't just flipping a switch, we need some gradual process.

**Comment by kimgr** [comment]
I'm not so happy with two binaries because of link times (on Windows) and download size. It seems silly to ship two 45MB executables just to vary the exit code.

I think a command-line arg would make sense for this.

**Comment by alanbirtles** [comment]
you could just write a wrapper bash script which runs iwyu and then fixes the return code or even runs the comiler if your build system needs the object files to be generated.

**Comment by jonesmz** [comment]
I'm no longer involved in the project that I wrote about in my previous comment, but do note that the project in question was on windows, where process creation, such as running a wrapper script, is very expensive and can slow down builds. As such, a wrapper script would have been really undesirable.

**Comment by JCash** [comment]
_First of all, thanks to the maintainers for a great tool!_

I too would like to raise the issue of not being able to use `iwyu` as a replacement for the compiler.
The fact that it fails a fixed build with `(foo.cpp has correct #includes/fwd-decls)` seems counter productive strange. I think it's ok to assume people are using different buildsystems that all work a bit differently.

Since the documentation says it is alpha status on the code, I think it's very much ok to reverse the behavior or add more flags to the compiler to control this behavior.

> you could just write a wrapper bash script which runs iwyu and then fixes the return code or even runs the compiler if your build system needs the object files to be generated.

Then, I suggest this is the built in approach which will then gets distributed to the users.

**Comment by Bu11etmagnet** [comment]
You can't use the exit status of `make CXX=iwyu` or `CXX=iwyu make` (or any tool which respects CXX) to decide whether your code is iwyu-clean, because the build will always fail. Even if iwyu pretends to succeed, the linker/librarian will get upset when it doesn't find any object files.

(CMake's iwyu support might not have this problem, if it treats iwyu separately from the compiler; but then, it already knows how to handle iwyu's non-zero exit code).

**Comment by JCash** [comment]
I realize I didn't fully understand that `iwyu`doesn't output valid object files. Probably a good idea to highlight a bit more in the docs.

**Comment by kimgr** [comment]
@JCash Right, IWYU is not a compiler, just a static analysis tool. It's the equivalent of `$(CC) -fsyntax-only t.c` with additional bells and whistles to analyze the includes.

And the reason it always exits with error is to cater for `make -k`. This is explained in https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-run.

But it _is_ an annoying run mode. I wonder if we should just have a switch to `include-what-you-use` that enables this fail-by-default thing, for people who use IWYU with GNU Make. But then the challenge is naming that switch :)

**Comment by rianquinn** [comment]
I am not sure what the status is of this, but we really needed this tool to work with CI, and we ran into a number of issues (one of which is talked about in this issue):
- Output is too verbose for large projects causing the CI log to be simply unusable. 
- We really need a way to get a proper exit code so that CI knows when an error has occurred. 
- The python script should stop when an error has been detected, otherwise you get a mess of compound issues. 
- CMake integrations is largely broken. If a toolchain is used, the IWYU args are not passed to the cross compilation environment. In addition, the exit code issue is also an issue with CMake.

To fix all of this, I made some simple changes that I outlined in the following issue which now allows us to use IWYU easily from CI:
https://github.com/include-what-you-use/include-what-you-use/issues/949

Hope this helps. The output looks like this BTW. It will only output add/remove if there is something to do, and only outputs when an error has occurred. For large projects, this is a lot easier to read IMO and it is far less verbose. Adding in the exit code changes, and it works more like I was expecting:
![image](https://user-images.githubusercontent.com/5932003/132102320-19a14a80-a335-4939-baed-e593311cb0d9.png)

**Comment by alokpr** [comment]
Any updates?

@kimgr I like the approach in this branch: https://github.com/kimgr/include-what-you-use/commits/exit-code

**Comment by kimgr** [comment]
Closed by #1011

**Comment by correaa** [comment]
> This is now documented here: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/InstructionsForUsers.md#using-with-cmake. But it only works if you already have a CMake system, obviously.

The link is broken.

**Comment by kimgr** [comment]
@correaa That page has now been folded into the readme: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#using-with-cmake
