### ISSUE TITLE
std::move does not require <utility> with template parameters

### ISSUE THREAD

**Issue by vmiklos** [include-what-you-use/include-what-you-use#636]
Hi,

Consider the following reproducer:

````
#include <ostream>

template <typename> struct A {};

struct B
{
    template <typename T> B(A<T>&& a) {}
};

template <typename T> void f(A<T>&& a) { B(std::move(a)); }
````

Then:

````
$ include-what-you-use -std=gnu++17 bad.cxx 

bad.cxx should add these lines:

bad.cxx should remove these lines:
- #include <ostream>  // lines 1-1

The full include-list for bad.cxx:
---
````

Note how std::move() is used, but <utility> is not present and that missing include is not detected. But in case the parameter of f() is not a template:

````
#include <ostream>

struct A {};

struct B
{
    B(A&& a) {}
};

template <typename T> void f(A&& a) { B(std::move(a)); }
````

Then this is recognized correctly:

````
$ include-what-you-use -std=gnu++17 good.cxx 

good.cxx should add these lines:
#include <utility>  // for move

good.cxx should remove these lines:
- #include <ostream>  // lines 1-1

The full include-list for good.cxx:
#include <utility>  // for move
---
````

I.e. if you have <utility> in such an input by accident, then IWYU suggests to remove it, while it should not.

Version:

````
$ include-what-you-use --version            
include-what-you-use 0.11 based on clang version 7.0.1-svn348686-1~exp1~20181213084532.54 (branches/release_70)
````

Please let me know if any more information is needed. Also, if you have some code pointers, I might be able to try to fix this myself -- though from what I learned about the Clang AST so far suggests that anything related to templates is not easy. :-)

Thanks,

Miklos

**Comment by kimgr** [comment]
Sorry for not picking this up sooner.

It looks like the dependent template arg mangles the AST completely:
```
`-FunctionTemplateDecl 0x55bcfe7343f0 <line:10:1, col:59> col:28 f
  |-TemplateTypeParmDecl 0x55bcfe734138 <col:11, col:20> col:20 referenced typename depth 0 index 0 T
  `-FunctionDecl 0x55bcfe734358 <col:23, col:59> col:28 f 'void (A<T> &&)'
    |-ParmVarDecl 0x55bcfe7342a0 <col:30, col:37> col:37 referenced a 'A<T> &&'
    `-CompoundStmt 0x55bcfe734550 <col:40, col:59>
      `-CXXUnresolvedConstructExpr 0x55bcfe734528 <col:42, col:56> 'B' 'B'
        `-CallExpr 0x55bcfe734500 <col:44, col:55> '<dependent type>'
          |-UnresolvedLookupExpr 0x55bcfe7344b0 <col:44, col:49> '<overloaded function type>' lvalue (no ADL) = 'move' 0x55bcfe017aa0 0x55bcfe127b60
          `-DeclRefExpr 0x55bcfe734470 <col:54> 'A<T>' lvalue ParmVar 0x55bcfe7342a0 'a' 'A<T> &&'
```

I think that `UnresolvedLookupExpr` hides away the details of the callee. Not sure what to do about it...

**Comment by vmiklos** [comment]
I looked into this briefly, but I didn't find anything, either. I guess the problem is that the template is not instantiated, so we don't really know which function will be called for std::move(), as the actual function (template) depends on the type of T.

I tried using shouldVisitTemplateInstantiations() in the AST visitor, but 1) it's not clear that's really necessary here 2) in this given example there is no instantiation at all, so it doesn't even help. Just noting it down here, so the next person doesn't waste time on this direction. :-)

**Comment by kimgr** [comment]
I did some more digging on this, and it turns out we have rudimentary handling for this case already :-)

In `VisitOverloadExpr` (of which `UnresolvedLookupExpr` is a derivative), there's code to look through decls in overload resolution. But it has a hard assumption that all overloads for a function are in the same file. That simplifies IWYU's job, because we only care about the file eventually, anyway.

And it turns out there are actually two `std::move` in the STL (sigh):
- https://en.cppreference.com/w/cpp/utility/move
- https://en.cppreference.com/w/cpp/algorithm/move

Since one is in `<utility>` and one is in `<algorithm>`, we give up and ignore it. It could be that we should special-case `std::move` in `VisitOverloadExpr`, but I guess this is just symptomatic of a larger problem where we would somehow need to perform full overload resolution to find the right callee.

**Comment by kimgr** [comment]
Yup, I can configure that removing the "same-file" check in `VisitOverloadExpr` fixes this issue, but only because the rvalue reference `std::move` happens to come before the container range `std::move` in the overload decls.

**Comment by aaronpuchert** [comment]
I'm running into the same issue from another end, I think. When using `std::vector::push_back`, it is suggested to me that I add `<algorithm>` for `std::max`, which is used in libstdc++ via `_M_realloc_insert` and `_M_check_len`. The call looks like this: `std::max(size(), __n)` or (minus addresses)

```
CallExpr <col:35, col:55> '<dependent type>'
|-UnresolvedLookupExpr <col:35, col:40> '<overloaded function type>' lvalue (no ADL) = 'max'
|-CallExpr <col:44, col:49> '<dependent type>'
| `-MemberExpr <col:44> '<bound member function type>' ->size
|   `-CXXThisExpr <col:44> 'const vector<_Tp, _Alloc> *' this
`-DeclRefExpr <col:52> 'std::vector::size_type':'unsigned long' lvalue ParmVar '__n' 'std::vector::size_type':'unsigned long'
```

(I'm not sure why the return type of the `size` member call is type-dependent — the `MemberExpr` can be resolved and has an independent return type.)

So the suggestion comes because the lookup is unresolved in `bits/stl_vector.h` and only resolved on instantiation in my source file.

Generally, this is expected: we can only say which overload is used when we plug in specific template arguments. If there is only one candidate we will always end up with that, but as was pointed out [before](#issuecomment-462125744), in the case of `std::move` there are two candidates in different headers. For `std::max` there are even four (two arguments or `std::initializer_list`, with or without comparison functor). All of them are officially included via <algorithm>, but libstdc++ has them in different files.

What we could do, at least for `std::move`, is to go by the number of arguments. The <utility> move has one parameter, whereas the <algorithm> move variants have at least three. That doesn't work for `std::max` though, because two of the overloads have two parameters. It would only work if Clang would remove the (unnecessary) type dependency.

**Comment by vmiklos** [comment]
Oh nice, thanks!
