### ISSUE TITLE
IWYU could not find stddef.h on Ubuntu 18.04

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#679]
I'm trying to use IWYU on my project on Ubuntu 18.04. I installed pre-build LLVM/Clang 8 and built IWYU with it.

My project was built successfully LLVM/Clang 8 and I then run IWYU on compile database. I got next errors:

In file included from /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring:42:
/usr/include/string.h:33:10: fatal error: 'stddef.h' file not found
#include <stddef.h>

stddef.h doesn't exist in /usr/include, but it installed with LLVM/Clang and IWYU could deduce location from compile command.

I'm not sure that this problem is with IWYU, it may be problem in Clang tooling.

**Comment by EugeneZelenko** [comment]
Same for float.h, limits.h, stdarg.h.

**Comment by JonasToth** [comment]
Having the same problem with gcc 7.3 as the referenced compiler for the includes, but clang as project compiler

**Comment by kimgr** [comment]
I guess this is issue #100 (described in some detail here: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-install)? 

`stddef.h` and others are the compiler's builtin headers, and clang searches for them relative to its own `argv[0]`. The builtin include path is not part of the compilation database. Since IWYU just links to the Clang library that implicitly adds this include path, IWYU has the same behavior. See doc link above for workarounds.

See also PR #576 and issue #484 for more information/discussion around this.

**Comment by EugeneZelenko** [comment]
But Clang path itself (argv[0]) is part of compilation database.

Bu the word, Clazy has same problem.

**Comment by EugeneZelenko** [comment]
I was pointed by Clazy author to link workaround (https://github.com/KDE/clazy/blob/master/README.md) and IWYU worked for me after link creation.

**Comment by JonasToth** [comment]
I figured out how to unbreak my system as well, but used a different approach.

The `compile_commands.json` is generated with cmake and I exploited `CXXFLAGS` in the configure step.

Say you use clang-7 as the compiler for you project (and linux!).

```
$ # Find locations that define 'stddef.h' and friends
$ locate stddef.h | sed -ne '/^\/usr/p'
> /usr/include/linux/stddef.h
> /usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h
> /usr/lib/llvm-7/lib/clang/7.1.0/include/stddef.h
> /usr/lib/llvm-8/lib/clang/8.0.1/include/stddef.h
> /usr/lib/llvm-9/lib/clang/9.0.0/include/stddef.h
```
Use the proper include directory, for clang-7 it would be `/usr/lib/llvm-7/lib/clang/7.1.0/include/`.

Recreate the `compile_commands.json` with

```
$ CXXFLAGS="-isystem /usr/lib/llvm-7/lib/clang/7.1.0/include" cmake <CONFIGURATION PARAMETERS>
$ # compile_commands.json should have the include directory for each translation unit (.cpp file)
```

Now the header is resolved properly. This flow would always work somewhat, you just need to get the include-directory right.

From my side this bug can be closed :)

**Comment by EugeneZelenko** [comment]
Thank you for other workaround! But I still think will be good idea to improve tooling run-time configuration, since different tools fail in same way and workarounds are needed as fixes. Tool working out of the box creates much better user experience :-)

**Comment by JonasToth** [comment]
That is true ;)

**Comment by kimgr** [comment]
I agree that it would be great to fix this, and that discussion is already covered by #100. So let's close this as a dupe (but thank you both for the different workaround suggestions)

**Comment by jonesmz** [comment]
FYI that I just ran into this on Ubuntu 20.04.

**Comment by Akuli** [comment]
I have always given `-I/usr/lib/llvm-8/lib/clang/8.0.1/include` or similar to IWYU when running it. Maybe the need for it should be mentioned in the README?

Sorry for not reading most of the conversation above. It's a bit tldr.

**Comment by wojdyr** [comment]
@jonesmz on Ubuntu 20.04 it can be fixed with `sudo apt install clang-9`

**Comment by Akuli** [comment]
@jonesmz I don't know what you're doing wrong, but I made a minimal version of my CI setup for you to look at. It runs IWYU correctly and fails because there is an unnecessary include. https://github.com/Akuli/3d-game-experiment/runs/3450419993

**Comment by firewave** [comment]
@jonesmz 
> Somehow Clang itself is able to determine the path to the system standard library, but IWYU is not.

The includes are also not coming from the `clang` package but from `libclang-common-<version>-dev`.

The problem arises when the installed Clang includes do not match the one used to build include-what-you-use (or do not exist at all). As long as they are in sync it works fine but if only one of them is updated while you will encounter the problem.

ubuntu is currently two versions behind (0.15 instead of 0.17) on 21.10 so you need to install the headers for clang 11 (i.e. `libclang-common-11-dev`) for it to work.

IIRC in the past I fixed this in the past by passing the current Clang includes with `-I /usr/lib/clang/<version>` to the include-what-you-use call. 

To me the issue seems like a dependency issue in the ubuntu package since it should be working out of the box. On rolling Kali Linux (which is based on Debian) it "just works". But they are using the latest version of include-what-you-use and the latest clang so they are in sync.

**Comment by blozano-tt** [comment]
> I figured out how to unbreak my system as well, but used a different approach.
> 
> The `compile_commands.json` is generated with cmake and I exploited `CXXFLAGS` in the configure step.
> 
> Say you use clang-7 as the compiler for you project (and linux!).
> 
> ```
> $ # Find locations that define 'stddef.h' and friends
> $ locate stddef.h | sed -ne '/^\/usr/p'
> > /usr/include/linux/stddef.h
> > /usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h
> > /usr/lib/llvm-7/lib/clang/7.1.0/include/stddef.h
> > /usr/lib/llvm-8/lib/clang/8.0.1/include/stddef.h
> > /usr/lib/llvm-9/lib/clang/9.0.0/include/stddef.h
> ```
> 
> Use the proper include directory, for clang-7 it would be `/usr/lib/llvm-7/lib/clang/7.1.0/include/`.
> 
> Recreate the `compile_commands.json` with
> 
> ```
> $ CXXFLAGS="-isystem /usr/lib/llvm-7/lib/clang/7.1.0/include" cmake <CONFIGURATION PARAMETERS>
> $ # compile_commands.json should have the include directory for each translation unit (.cpp file)
> ```
> 
> Now the header is resolved properly. This flow would always work somewhat, you just need to get the include-directory right.
> 
> From my side this bug can be closed :)

@JonasToth 

Thank you, I was hitting the same problem 5 years later.

To fix, I had to find out what are the default compiler search paths.

I am using libc++ instead of libstdc++.

I had to ask clang for search paths:
```
$ clang++-17 -stdlib=libc++ -E -x c++ - -v < /dev/null
```

Then I had to do:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem /usr/lib/llvm-17/include/c++/v1")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem /usr/lib/llvm-17/lib/clang/17/include")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem /usr/local/include")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem /usr/include/x86_64-linux-gnu")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem /usr/include")
```
