### ISSUE TITLE
Wrong forward declaration removal suggestion with --no_fwd_decls

### ISSUE THREAD

**Issue by fabledpig** [include-what-you-use/include-what-you-use#702]
In this simple test case:
```
namespace NS {
  class Foo;

  template<class T>
  struct FWDOnly {
    T *t;
  };

  struct Bar {
    FWDOnly<Foo> ptr;
  };
}
```

IWYU with `--no_fwd_decls` suggests to remove the forward declaration of class Foo, however this causes a compilation error. This does not happen without the --no_fwd_decls option.

**Comment by fabledpig** [comment]
This was on branch clang_7.0 and I just saw that this is already fixed on master, so closing this.

**Comment by kimgr** [comment]
Phew, thanks! :)

**Comment by fabledpig** [comment]
I backported the fix to clang_7.0 but in the following case it still suggests a bad removal:
```
// test.hpp
#pragma once

class Foo;

class Bar {
  Foo *ptr;
};

//test.cpp
#include "test.hpp"

class Foo {};
```
It says that the `class Foo;` line from test.hpp should be removed.

I can't test this on master as I don't have clang 9, so please see if it's also not quit right there either.

**Comment by kimgr** [comment]
I can confirm that the second example fails with `--no_fwd_decls`. Upping the log level it seems like the handling of 'backwards' includes is somehow setting this use to ignored.

I think it's because somewhere the used decl is canonicalized to its definition, which is in `test.cpp`, and `test.h` should not include `test.cpp`. There's some room for improvement there.
