### ISSUE TITLE
Incorrect analysis of required complete types

### ISSUE THREAD

**Issue by mohitmv** [include-what-you-use/include-what-you-use#835]
The calculation of required-complete-types is wrong.

Consider this header `a.hpp`

```C++
struct S;
// #include "s.hpp"

S F(int x, int y);
```

This function `F` can be declared with just forward declaration of `S`. iwyu works if I forward declare `S`. (i.e. it doesn't complain). However  if I include the `s.hpp` then it doesn't complain saying `S could be forward declared. no need of s.hpp`

Note: If I declare a signature of kind `void F(S&);`, then iwyu works fine. i.e. it complains that `S could be forward declared. No need of including s.hpp`.

**Comment by kimgr** [comment]
That's by design, see https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhatIsAUse.md#author-intent.

**Comment by mohitmv** [comment]
@kimgr - Ok fine but It is good to expose these choices in command line options of iwyu binary. It actually makes sense to dedicate a flag for each of these choices and let the end user choose for themselves. Of course default option one can be what it is right now.

If this change looks good to you or other authors, I am happy to create a pull request. I was reading the source code. It's pretty much understandable and well documented.

**Comment by kimgr** [comment]
@mohitmv We've tried carefully in the past to avoid policy switches like this, in part because our testing becomes unmanageable (essentially we'd need to run all tests with both configurations for perfect coverage).

But the current behavior is also kind-of reasonable:

* It reduces coupling by making sure that when you include a header, you have a ready-to-use, self-sufficient unit of functionality
* In the cases where that introduces a build time regression, you can use the forward-declare hint to disable it

I think the current tradeoff is basically right.

It would be interesting to see a pull request, of course, but I'm not really prepared to promise to accept it.

**Comment by mohitmv** [comment]
Makes sense. @kimgr
