### ISSUE TITLE
Meson example

### ISSUE THREAD

**Issue by Petross404** [include-what-you-use/include-what-you-use#868]
Hello folks. I managed to use `iwyu` with CMake like this :
```cmake
if(ENABLE_INCLUDE_WHAT_YOU_USE)
	message(STATUS "Configuring include-what-you-use for TARGET: ${NAME_OF_TARGET}")
	find_program(iwyu_path NAMES include-what-you-use iwyu)
	if(NOT iwyu_path)
		message(FATAL_ERROR "Could not find the program include-what-you-use.")
		message(FATAL_ERROR "Configure the project with -DINCLUDE_WHAT_YOU_USE=OFF")
	else()
		set_property(TARGET "${NAME_OF_TARGET}" PROPERTY CXX_INCLUDE_WHAT_YOU_USE ${iwyu_path})
	endif()
endif(ENABLE_INCLUDE_WHAT_YOU_USE)
```

Can anyone help me doing something relevant with Meson?

**Comment by kimgr** [comment]
I don't know exactly what CMake does behind the scenes, or how Meson works at large.

But I can tell you how `include-what-you-use` works --

* It's a compiler replacement that accepts all the same arguments as Clang
* Additionally, you can pass IWYU-specific arguments using an `-Xiwyu` prefix arg, e.g. `-Xiwyu --verbose=5`
* It does not generate any object files, it's just a front-end action
* It always exits with non-zero exit code (for historical reasons), the "success" exit code is 1

So the way to integrate in a build system is to generate a new target where `clang` (or other compiler) is replaced with `include-what-you-use` in the compile commandline for every source file, and tack on any additional arguments.

For GNU Make, that's easily done on invocation with something like `CC=include-what-you-use CXX=include-what-you-use make`, but different build systems have different workflows.

Maybe you can take this to a Meson forum, armed with that knowledge? Good luck!

**Comment by i-ky** [comment]
@Petross404, if Meson can generate `compile_commands.json`, I would recommend you go [that route](https://github.com/include-what-you-use/include-what-you-use#using-with-a-compilation-database). At work we use CMake and I did an integration using `CXX_INCLUDE_WHAT_YOU_USE`, but now I regret that, because we also use `ccache` and unfortunately IWYU results aren't cached, so having `CXX_INCLUDE_WHAT_YOU_USE` in the loop slows down rebuilds. Our integration with [Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/index.html), on the other hand, is based on `compile_commands.json` (because [`CMAKE_CXX_CLANG_TIDY`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_CLANG_TIDY.html) wasn't available in CMake version we use) and is completely independent of build process. I find this is a better approach.

**Comment by Petross404** [comment]
Thank you both!

**Comment by kimgr** [comment]
@i-ky Thanks for the experience report! I haven't had a chance to try IWYU+cmake myself, so I wasn't aware of the end-to-end behavior.
