### ISSUE TITLE
Should specify c++ standard for compiler

### ISSUE THREAD

**Issue by Phantomape** [include-what-you-use/include-what-you-use#880]
Hi, I'm trying to build IWYU with clang-11, however it gave a lot of errors complaining about ```error: ‘enable_if_t’ in namespace ‘std’ does not name a template type```
![image](https://user-images.githubusercontent.com/8809221/108464224-b3be2a80-72ba-11eb-8dd7-33dd80cb0657.png)
I manually specified the version and now it works
![image](https://user-images.githubusercontent.com/8809221/108464347-e6682300-72ba-11eb-9f42-2829821e5896.png)
Maybe consider adding this line in the CMakeLists.txt?

**Comment by kimgr** [comment]
I wonder if this is the same as https://github.com/include-what-you-use/include-what-you-use/issues/867? Are you using Apple's Clang compiler?

But yeah, I think we'll have to fall back to specifying it ourselves, I haven't heard anything on the matter from the llvm folks.

**Comment by Phantomape** [comment]
Clang compiler? presumably yes ... I guess specifying the c++ standard instead of relying on the default behavior of external software would make the installation more robust.

**Comment by kimgr** [comment]
I'm specifically interested in whether it's Apple Clang -- can you get me the output of `clang --version`? It has a bug where it defaults to an older language version.

The reason I just don't fix this in IWYU is because IWYU itself only requires C++11 and the C++14 dependency comes from LLVM headers. I would like for LLVM to expose that through its CMake config.

That said, it would probably be much easier to work around in IWYU. Maybe I should just introduce use of some random C++14 feature :)

**Comment by kimgr** [comment]
Added an explicit `-std=c++14` in our CMake.
