### ISSUE TITLE
Documentation not honored by IWYU - re-exporting symbols

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#900]
Hi,

The IWYU documentation says:

```
Here is an example of the rule in action:

foo.h:
  class Foo { ... }

bar.h:
  #include "foo.h"
  Foo CreateFoo() { ... }
  void ConsumeFoo(const Foo& foo) { ... }

baz.cc:
  #include "bar.h"
  ConsumeFoo(CreateFoo());
In this case, IWYU will say that baz.cc does not need to #include "foo.h", since bar.h re-exports it.
```

This doesn't seem to be the case in this example test:

```
// foo.h
struct Foo
{
    int x;
};
```

```
// bar.h
#include "foo.h"

inline Foo makeFoo()
{
    return Foo{};
}
```

```
// baz.cpp
#include "bar.h"

void f()
{
    Foo x = makeFoo();
}
```

Here, IWYU requests that `baz.cpp` must include `foo.h`. Isn't that contradicting the documentation?

**Comment by kimgr** [comment]
Yes, so it seems.

I wonder how and when this broke, and why it's not covered by tests... What happens if you make the example verbatim the same as the docs (no `inline`, you can get away with just declarations)? I wonder if there's some tiny detail in your experiment that tips the scales.

**Comment by carlosgalvezp** [comment]
Ok so it seems the main difference is:
```
ConsumeFoo(createFoo());
```

vs:

```
Foo f = CreateFoo();
ConsumeFoo(f);
```

The last one triggers the warning. Still the intent is the same, right?

**Comment by kimgr** [comment]
@carlosgalvezp I'm not sure... I think since the type is explicitly mentioned in the second example, that might trigger IWYU to require it.

Let's pretend `ConsumeFoo` and `createFoo` in the first example were both changed to return and consume an `int` instead of `Foo`. `bar.h` would be changed not to include `foo.h`. There is no effect on `baz.cc` here -- it never included `foo.h`, and it silently keeps working.

In the second example, `Foo` is explicitly mentioned, and changing `ConsumeFoo`/`CreateFoo` to work on `int` would lead to `foo.h` being removed from `bar.h`. If `baz.cc` itself didn't include `foo.h` it would break as part of that refactor (even if `baz.cc` is just an innocent bystander).

If, as part of that refactor `Foo f = CreateFoo();` is changed to `int f = CreateFoo();`, IWYU will suggest that `Foo` be removed from `baz.cc`, as it's no longer used.

If it's not changed, either `baz.cc` will no longer compile, or `Foo` has an implicit conversion from `int`, in which case it should still be included.

So from that perspective, this looks like the right behavior. But it's always possible to think of it from some other angle, where it seems broken :-)

**Comment by carlosgalvezp** [comment]
@kimgr You've convinced me, I agree with your explanation :) I guess I got confused by the doc text "IWYU will say that baz.cc does not need to #include "foo.h", since bar.h re-exports it". I understood that this would happen always, regardless of how `createFoo` is used. Perhaps it would be nice to have this example as clarification?
