### ISSUE TITLE
Request - allow disabling the print of "full include-list"

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#983]
Hi,

IWYU will print the changes needed but also the final, full include list. This information is redundant and generates a lot of noise in the build logs. Would it be possible to make this opt-in/opt-out?

Thanks!

**Comment by kimgr** [comment]
Are you on a platform where it would be possible to use a shell script to filter it out instead?

**Comment by carlosgalvezp** [comment]
Sure, everything is possible :) I just wonder what benefit this printout brings. It's like a compiler pointing out that a semicolon is missing and then printing how the whole file is supposed to look like after the fix is applied - that wouldn't make sense, the user is interested in knowing what to fix.

Besides, IWYU doesn't preserve formatting and breaks include groups - they are all put together in the same group. If people copy-paste that list blindly then they violate their include formatting guide, which causes even more developer friction:

```
#include <c_header_a.h>
#include <c_header_b.h>

#include <cppheader_a>
#include <cppheader_a>
```

IWYU will say it should look like:

```
#include <c_header_a.h>
#include <c_header_b.h>
#include <cppheader_a>
#include <cppheader_a>
```

**Comment by kimgr** [comment]
In a project a long time ago, we actually did just copy/paste and hand-edit any problematic includes. That got us to a more complete include graph fairly quickly.

Even a small option such as this splits the tool into two two modes that both require testing and attention from downstream tools (e.g. `fix_includes.py`).

I think the IWYU output is pretty suboptimal overall, but I also can't really judge the pros/cons of alternative outputs and say whether they effectively make a big difference. And since all our testing and tooling is built on the current output, I'd rather err on the side of preservation.

I have very limited time for IWYU (on the order of half an hour a week), so I have many other priorities for it that trump customized output.

**Comment by carlosgalvezp** [comment]
Understandable, I will drop the request then. Thanks!
