### ISSUE TITLE
Use more idiomatic exit codes from IWYU tools

### ISSUE THREAD

**Issue by kimgr** [include-what-you-use/include-what-you-use#985]
IWYU's use of exit codes is a bit of a mess:

* `include-what-you-use` currently returns 1 for critical errors, and 2 + `number-of-suggested-edits` for success
* `include-what-you-use` exit code can overflow (if more than 255 edits were suggested)
* `include-what-you-use` success codes can leak into reserved shell exit codes (if more than 100 edits were suggested) 
* `fix_includes.py` currently returns the number of edits made
* `iwyu_tool.py` currently translates all non-zero exit codes into 1

This means all modes signal failure even if everything ran to completion and was A-OK according to IWYU policy.

IWYU has been like this forever, but now it's confusing enough that I think it's time to just harmonize and return 0 if everything went well, and non-zero if not.

The CMake folks have acknowledged that their integration doesn't look at exit code, and so won't be affected: https://discourse.cmake.org/t/planning-change-that-might-break-lang-include-what-you-use/4598/3

Suggested changes off the top of my head:
- [x] Return zero from `include-what-you-use` if no changes were suggested
- [x] Return 1 from `include-what-you-use` if there's a critical error (e.g. invalid command-line args)
- [x] Add override command-line switch to go back to `make -k`-friendly behavior. For example: `-Xiwyu --fail-always`
- [x] Add command-line switch to return 1 if changes are suggested. For example: `-Xiwyu --fail-on-suggestions`
- [x] Change `iwyu_tool.py` to return max(exit codes of all invocations)
- [x] Change `fix_includes.py` to return 0 for success, 1 for error
- [x] Update README.md
- [x] Update manpage
- [x] Update test framework to be more stringent around exit codes

Probably more to come here.

**Comment by kimgr** [comment]
Related:
* #904 
* #440 
* #790

**Comment by vmiklos** [comment]
Is the cmake link wrong? :)

**Comment by kimgr** [comment]
@vmiklos Oops, yes. That one doesn't even work for me :-). Fixed.

**Comment by firewave** [comment]
Some addition on "prior art" already mentioned in https://github.com/include-what-you-use/include-what-you-use/pull/904#issuecomment-1022443591.

Regarding the usage of a configurable exit code in the GCC/Clang sanitizers. This appears to be only available (or only documented?) for ThreadSanitizer where it default to `66` (see https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags). The use case there is different since it changes the behavior of the executable and so you need to be able to differentiate an exit caused by the sanitizer from an actual one of a program. But this might also apply to include-what-you-use since it can be used as a compiler drop-in.

**Comment by alejandro-colomar** [comment]
`Acked-by: Alejandro Colomar <alx.manpages@gmail.com>`

Hi Kim,

Thanks!  I think this is a good change.  The rationale[1] for the old design was broken, and was only there to workaround broken Makefiles.

[1]:

> (include-what-you-use always exits with an error code, so the build system knows it didn't build a .o file. Hence the need for -k.)

To that, I'd comment that, proper Makefile rules wouldn't rely on iwyu(1) generating .o files.  See for example (part of) a Makefile of mine:

```
UNITS_c   := $(sort $(shell find $(SRCDIR) -type f | grep '\.c$$'))
UNITS_iwyu:= $(patsubst $(SRCDIR)/%.c,$(builddir)/%.iwyu.touch,$(UNITS_c))

DEFAULT_IWYUFLAGS := -Xiwyu --no_fwd_decls
EXTRA_IWYUFLAGS   :=
IWYUFLAGS         := $(DEFAULT_IWYUFLAGS)
IWYUFLAGS         += $(EXTRA_IWYUFLAGS)

IWYU := iwyu

$(UNITS_iwyu): $(builddir)/%.iwyu.touch: $(SRCDIR)/%.c Makefile \
                                         $(builddir)/%.d | $$(@D)/.
	$(info IWYU		$@)
	$(IWYU) $(IWYUFLAGS) $(CPPFLAGS) $(CFLAGS) $<
	touch $@

analyze-iwyu: $(UNITS_iwyu)
analize: analyze-clang-tidy analyze-iwyu ...
```

I think this is how a Makefile that uses iwyu(1) should look like, and a non-zero exit status just messes with it.

Also, could I ask that whatever exit codes you choose, you document them with more detail in the manual page?  See for example <http://www.alejandro-colomar.es/man/man6/chess-mv.6.html>.

I wrote that Makefile today, and as you can guess was quite surprised that iwyu(1) didn't return 0 while verbose showed no errors, and since the current manual page doesn't document the different exit statuses, it took me a while to find what to do.  So, please fix this bug/feature :)

**Comment by alejandro-colomar** [comment]
I'd use the following:

EXIT_SUCCESS: No errors.  No changes suggested.
EXIT_FAILURE: No critical errors.  Changes suggested.
Some [sysexits.h(0)](http://www.alejandro-colomar.es/man/man0/sysexits.h.0.html)  errors for critical errors.

**Comment by kimgr** [comment]
@alejandro-colomar `sysexits.h` is a POSIX thing, IWYU targets Windows too.

**Comment by alejandro-colomar** [comment]
You could just add the header file to the IWYU sources.  glibc's history shows the last change to the file was in 1999, so I expect it to not change soon :)

However, `EXIT_FAILURE` for everything is a simple alternative.

**Comment by kimgr** [comment]
Here we go: https://github.com/include-what-you-use/include-what-you-use/pull/1011
